### ISSUE TITLE
read_layouts can encode incorrect targets if many columns are empty

### ISSUE THREAD

**Issue by taylo5jm** [hemoshear/assayr2#1]
Pasted a screenshot of a layout where this happens. 

![screen shot 2018-12-07 at 1 49 04 pm](https://user-images.githubusercontent.com/6889169/49666706-e73c7380-fa26-11e8-9651-f19be6258ed0.png)

Perhaps, we should add an optional argument to read_layouts that overrides the default formula that the function uses to encode targets.

**Comment by nathancday** [comment]
`read_color_layouts()` is the long term fix to this problem
