### ISSUE TITLE
Add tryCatch support to par_stats()

### ISSUE THREAD

**Issue by nathancday** [hemoshear/assayr2#43]
I think returning an empty data.frame/tibble make a lot of sense to bake into par_stats() now.

**Comment by taylo5jm** [comment]
I think a tryCatch mechanism would be useful, but more useful at the `make_*` level. The only way to implement tryCatch in `parStats` is to return an empty data frame if one or more calls to make_stats fails, but we want to get the output of `make_stats` for elements that do not fail, even if some do.

**Comment by nathancday** [comment]
I was tinkering with this and the more I think about it, the more I like using the existing adverbs from `purrr` instead of changing the internals of the `make_Xs`.

# psuedo-code
model_list <- list(good_mod, bad_mod)
map(model_list, make_stats) # raises an error
map(model_list, possibly(make_stats, tibble())) # list of tibbles with the second one empty

This was originally an idea to make the functions easier/smoother to use but wrapping in `possibly()` seems pretty smooth and prevents the bad scenario of warnings just being swept under the rug.
